[package]
name = "htmlize"
version = "0.5.1"
authors = ["Daniel Parks <oss-htmlize@demonhorse.org>"]
description = "Encode and decode HTML entities in UTF-8"
homepage = "https://github.com/danielparks/htmlize"
repository = "https://github.com/danielparks/htmlize"
readme = "README.md"
keywords = ["html", "entities", "escape", "unescape", "encode", "decode"]
categories = ["web-programming", "encoding"]
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
default = []
unescape = ["serde_json", "phf", "phf_codegen"]

[build-dependencies]
phf = { version = "0.11.1", default-features = false, optional = true }
phf_codegen = { version = "0.11.1", optional = true }
serde_json = { version = "1.0", optional = true }

[dependencies]
phf = { version = "0.11.1", default-features = false, optional = true }

[dev-dependencies]
assert2 = "0.3.7"
