[package]
name = "htmlize"
version = "0.5.0"
authors = ["Daniel Parks <oss-htmlize@demonhorse.org>"]
description = "Encode and decode HTML entities in UTF-8"
homepage = "https://github.com/danielparks/htmlize"
repository = "https://github.com/danielparks/htmlize"
readme = "README.md"
keywords = ["html"]
categories = ["web-programming", "encoding"]
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[build-dependencies]
serde_json = "1.0"

[dependencies]
phf = { version = "0", features = ["macros"] }

[dev-dependencies]
assert2 = "0.3.7"
