[package]
name = "html_entities"
version = "0.1.0"
authors = ["Daniel Parks <dp+git@oxidized.org>"]
description = "Encode and decode HTML entities in UTF-8"
license = "MIT OR Apache-2.0"
edition = "2018"

[build-dependencies]
serde_json = "1.0"

[dependencies]
phf = { version = "0", features = ["macros"] }
